# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: "Liam Hauw" # Website name
baseURL: 'https://example.com/' # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  # Docs options
  - _target:
      path: /docs/**
    backlinks: false
    show_date: true
    reading_time: true
    share: false
    profile: true
    commentable: false
    editable: false
    pager: true
    show_related: true
    show_breadcrumb: true
    header:
      navbar:
        enable: true
    highlight_name: true
  # Projects options
  - _target:
      path: /blogs/**
    backlinks: false
    show_date: true
    reading_time: true
    share: false
    profile: true
    commentable: false
    editable: false
    pager: true
    show_related: true
    show_breadcrumb: true
    header:
      navbar:
        enable: true
    highlight_name: true
  # Blogs options
  - _target:
      path: /docs/**
    backlinks: false
    show_date: true
    reading_time: true
    share: false
    profile: true
    commentable: false
    editable: false
    pager: true
    show_related: true
    show_breadcrumb: true
    header:
      navbar:
        enable: true
    highlight_name: true


############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
enableInlineShortcodes: true
disableAliases: true
outputs:
  home: [HTML, RSS, WebAppManifest, headers, redirects, backlinks]
  page: [HTML]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
