title: "Liam Hauw"
baseURL: 'https://example.com/'

############################
## PAGE OPTIONS
############################

cascade:
  - _target:
      path: /docs/**
    show_date: false
    show_date_updated: false
    editable: true
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  - _target:
      path: /blog/**
    show_date: true
    show_date_updated: true
    reading_time: true
    share: false
    profile: true
    commentable: false
    editable: true
    pager: true
    show_related: true
    share: false
    show_breadcrumb: false
    header:
      navbar:
        enable: true

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
enableInlineShortcodes: true
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, WebAppManifest, headers, redirects]
  page: [HTML]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 85
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
