# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Docs
    url: docs/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Blogs
    url: blogs/
    weight: 40
  - name: About
    url: about/
    weight: 50
