# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Liam Hauw personl website'
    twitter: 'Liam Hauw'
  analytics:
    google_analytics: ''
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: 'sVH8ZixkFx5eeeLTUTEuChwFdELkrA7n'
  verification:
    google: 'BzQwJPjBsb_Etsyllnh7LgRwIifs4qbDyi_VUj3GupQ'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      filename: "logo.svg"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Liam Hauw'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/liamhauw/liamhauw.github.io/'
    content_dir: 'content'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
  comment:
    provider: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
