# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: ''
    description: 'A personal website powered by Liam Hauw.'
    twitter: 'LiamHauw'
  analytics:
    google_analytics: ''
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: 'sVH8ZixkFx5eeeLTUTEuChwFdELkrA7n'
  verification:
    google: 'm_xZfpIqhYgFZi8s-b-XAO3E38oQG2H8NpoR_KPBxtM'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Get Started"
      url: "https://hugoblox.com/templates/details/docs/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Liam Hauw'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/liamhauw/liamhauw.github.io/'
    content_dir: 'content'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/liamhauw/liamhauw.github.io/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/liamhauw/liamhauw.github.io/issues/new).'
  comment:
    provider: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
